import fs from 'node:fs';
import path from 'node:path';
const packages = ['typescript', 'react', 'react-dom', 'scheduler', 'cytoscape'];
const sections = ['Third-party notices for bundled Code X-Ray runtime dependencies.\nGenerated by scripts/notices.mjs.\n'];
for (const name of packages) {
  const directory = path.join('node_modules', name);
  const info = JSON.parse(fs.readFileSync(path.join(directory, 'package.json'), 'utf8'));
  const license = fs.readdirSync(directory).find(file => /^license(?:\.txt|\.md)?$/i.test(file));
  if (!license) throw new Error(`Missing runtime license for ${name}`);
  sections.push(`\n${'='.repeat(72)}\n${name} ${info.version} — ${info.license}\n${'='.repeat(72)}\n${fs.readFileSync(path.join(directory, license), 'utf8')}`);
  const notices = fs.readdirSync(directory).filter(file => /^ThirdPartyNoticeText\.txt$/i.test(file));
  for (const file of notices) sections.push(fs.readFileSync(path.join(directory, file), 'utf8'));
}
fs.writeFileSync('THIRD_PARTY_NOTICES.txt', sections.join('\n'));
